### ISSUE TITLE
Centos7 make 报错

### ISSUE THREAD

**Issue by slightun** [fztcjjl/metoo#18]
make 时报下面错误，请问需要改哪里呢？

cc -g -O2 -Wall -fPIC --shared lualib-src/lua-log.c -o luaclib/log.so
lualib-src/lua-log.c:1:10: fatal error: lua.h: No such file or directory
 #include <lua.h>
          ^~~~~~~
compilation terminated.
make: *** [luaclib/log.so] Error 1

**Comment by slightun** [comment]
修改了下 Makefile，指定 lua 路径，可以了。

$(LUA_CLIB_PATH)/log.so : lualib-src/lua-log.c | $(LUA_CLIB_PATH)
	$(CC) $(CFLAGS) $(SHARED) $^ -o $@  -I skynet/3rd/lua

**Comment by lghelp** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by lghelp** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
