### ISSUE TITLE
msgagent 是如何将push消息发送到客户端的？

### ISSUE THREAD

**Issue by BorgLee** [fztcjjl/metoo#6]
如题，望解答。

**Comment by fztcjjl** [comment]
msgagent.lua: msg_dispatch->do_server_push

**Comment by BorgLee** [comment]
msg_dispatch 是注册的client 协议 而CMD.push是lua协议 怎么会进入到msg_dispatch里的呢？

**Comment by fztcjjl** [comment]
CMD.push只是把要推送的消息存放到push_queue队列而已

**Comment by BorgLee** [comment]
但是msg_dispatch 不是由client类型的消息触发的吗？如果没有任何地方发送过client的消息 那么这个是如何触发msg_dispatch的呢？

**Comment by fztcjjl** [comment]
msg_dispatch调用了do_server_push,do_server_push会从push_queue队列取，然后打包，然后返回给gate，你再认真看看

**Comment by BorgLee** [comment]
那是不是必须要有个地方发送client类型 netmsg的name为netmsg.ServerPushRequest的才可以触发push_queue里需要push的数据呢？那么这个在哪里触发呢？

**Comment by fztcjjl** [comment]
发送给客户端，在msg_server.lua中，你看懂了整个消息服务器的 request response模式没有。推送的消息跟普通消息并没有本质区别
