### ISSUE TITLE
make出错了

### ISSUE THREAD

**Issue by 603010999** [fztcjjl/metoo#7]
编译这个需要其他什么条件吗，skynet可以编过

**Comment by fztcjjl** [comment]
只能在linux平台下make，如需在其他平台编译，请修改Makefile中的PLAT ?= linux

**Comment by 603010999** [comment]
是linux系统，是我的lua.h路径不对吗，求解答。前面因为lua版本不对，重装了lua

make[1]: Nothing to be done for `all'.
make[1]: Leaving directory`/home/aslan/work/metoo/lualib-src/pbc/binding/lua53'
cc -g -O2 -Wall -fPIC --shared lualib-src/lua-log.c -o luaclib/log.so
lualib-src/lua-log.c:1:17: error: lua.h: No such file or directory
lualib-src/lua-log.c:2:21: error: lauxlib.h: No such file or directory
lualib-src/lua-log.c:370: error: expected ')' before '_' token
lualib-src/lua-log.c:417: error: expected ')' before '_' token
lualib-src/lua-log.c:423: error: expected ')' before '_' token
lualib-src/lua-log.c:439: error: expected ')' before '_' token
lualib-src/lua-log.c:455: error: expected ')' before '_' token
lualib-src/lua-log.c:468: error: expected ')' before '_' token
lualib-src/lua-log.c:481: error: expected ')' before '_' token
lualib-src/lua-log.c:496: error: expected ')' before '_' token
make: **\* [luaclib/log.so] Error 1

**Comment by MacroGu** [comment]
我在重新安装 lua 5.3.2 版本之后， 解决了这个问题
